name: build-cv

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Latex
      run: sudo apt-get update -q && sudo apt-get install -qy texlive-full python-pygments gnuplot poppler-utils
    - name: Build CV
      run: latexmk -cd -f -interaction=batchmode -pdf $GITHUB_WORKSPACE/CV-main_page.tex
    - name: convert to png
      run: pdftoppm CV-main_page.pdf CV-Nils-Stein -png
    - name: deploy to gh-pages
      run: |
        ls -al
        mv CV-main_page.pdf ../CV-Nils-Stein.pdf
        mv CV-Nils-Stein-1.png ../CV-Nils-Stein.png
        git fetch
        git checkout gh-pages
        mv ../CV-Nils-Stein.pdf .
        mv ../CV-Nils-Stein.png .
        git add CV-Nils-Stein.pdf
        git add CV-Nils-Stein.png
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "$(date '+%d/%m/%Y %H:%M:%S') updated CV"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'gh-pages'
